FILE_PATH: src/main/resources/files/
API_V1: /api/v1/
BATCH_SIZE: 1000

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Ala_Ma_K0ta
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
    generate-ddl: true
    show-sql: true  # set this to true to see the SQL statements in your logs
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

# Links
logging:
    level:
      com.project.app: debug
# https://stackoverflow.com/questions/34177873/max-limit-of-multipartfile-in-spring-boot