FILE_PATH: src/main/resources/files/
API_V1: /api/v1/
BATCH_SIZE: 1000


server:
  port: 8081

spring:
  datasource:
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
    generate-ddl: true
    database-platform: org.hibernate.dialect.HSQLDialect